In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import time
import numpy as np
import os
import pandas as pd
from collections import defaultdict
pd.options.display.max_columns = 100
pd.options.display.max_rows = 130

In [3]:
from utils_shared_hanzi_shorts import (
    data_settings_by_char,
    enhance_data_settings, get_filtered_words, load_video_configs,
    get_character_counts,
    stitch_audios, draw_vocab_list_whole_image, 
    create_video_with_highlights, create_video_without_highlights
)
from utils_shorts import (
    create_directories
)
from utils_data import (load_raw_data, check_dups)

In [9]:
truly_load_data = False
df_all_vocab = load_raw_data(truly_load_data=truly_load_data)
df_dups = check_dups(df_all_vocab)
print(df_all_vocab.shape)
print(f'# duplicate vocab: {len(df_dups)}')
df_all_vocab.head(3)

(7665, 38)
# duplicate vocab: 0

,id,chinese,pinyin,english,type,priority,category1,category2,cat_v3,cat2_v3,cat3_v3,hsk_level,known,known_pinyin_prompt,known_english_prompt,quality,word1,word1_english,word2,word2_english,word3,word3_english,word4,word4_english,voice_zh,voice_en,video_notes,sentence,sentence_pinyin,sentence_english,date,source1,source2,funny,per,adu,slang,phonetic
0,1,房贷,fáng dài,mortgage,word,1,life,NaN,Finance & Economy,NaN,借贷与负债,MISSING,1.0,1.0,2.0,1.0,房子,house,贷款,loan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,他每个月都要还房贷,Ta měi gè yuè dōu yào huán fángdài,He has to pay his mortgage every month,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
1,2,白天,bái tiān,daytime,word,2,time,NaN,Time,NaN,时间段 / 时长,1.0,2.0,1.0,1.0,1.0,白,white,天,day,NaN,NaN,NaN,NaN,NaN,NaN,NaN,白天很热晚上比较凉快,Báitiān hěn rè wǎnshàng bǐjiào liángkuai,It is hot in the daytime and cooler at night,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
2,3,组成,zǔ chéng,to form;make up,word,3,general,NaN,Language & Expression,NaN,逻辑与结构,MISSING,5.0,5.0,5.0,3.0,组,set,成,become,NaN,NaN,NaN,NaN,NaN,NaN,NaN,水是由氢和氧组成的,Shuǐ shì yóu qīng hé yǎng zǔchéng de,Water is made up of hydrogen and oxygen,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN

# Settings

In [11]:
audio_settings = {
    'voice_name_zh': 'zh-CN-XiaoxiaoNeural',
    'audio_plan': 'ctitle_c2word',
    'pause_ms_beginning': 150,
    'pause_ms_within_word': 200,
    'pause_ms_between': 500,
}

# '天', '金', '物', '语', '时', '红', '公', '发', '自', '一', '山', '头', '花', '外', '手', '生', 
chosen_char= '生'

video_configs = load_video_configs()

In [15]:
# from edge_tts import list_voices, Communicate
# def single_tts_call(text, voice_name, output_file_name):
#   communicate = Communicate(text, voice_name)
#   communicate.save_sync(output_file_name)

# # Make dict of lists of words for text to speech
# # Or just directly do tts for these lists
# for char, settings in data_settings_by_char.items():
#     if char not in ['地', '水', '动']:
#         print(f"Processing character: {char}")
#         data_settings = data_settings_by_char[char]
#         data_settings = enhance_data_settings(data_settings)
#         create_directories(data_settings)
#         df_filt = get_filtered_words(df_all_vocab, data_settings)
#         words_to_tts = [data_settings['shared_char']] + df_filt['chinese'].values.tolist()
#         for word in words_to_tts:
#             output_file_name = f'output/shared_char_shorts/{char}/audio_files/{word}.mp3'
#             print(char, word)
#             if not os.path.exists(output_file_name):
#                 single_tts_call(word, 'zh-CN-XiaoxiaoNeural', output_file_name)

In [ ]:
for char, settings in data_settings_by_char.items():
    if char not in ['地', '水', '动']:
        data_settings = data_settings_by_char[char]
        data_settings = enhance_data_settings(data_settings)
        df_filt = get_filtered_words(df_all_vocab, data_settings)

        data_settings['n_words_total'] = len(df_filt)
        data_settings['n_parts'] = int(np.ceil(len(df_filt) / data_settings['n_words_per_video']))
        print(f"{char}: {len(df_filt)} words, {data_settings['n_parts']} parts")

        # Decrease spacing if necessary
        if data_settings['n_words_per_video'] == 11:
            video_configs['words_settings']['spacing'] = 48
        elif data_settings['n_words_per_video'] == 12:
            video_configs['words_settings']['spacing'] = 40

        for current_part in range(1, data_settings['n_parts'] + 1):
            # Determine vocabulary in current part
            data_settings['current_part'] = current_part
            start_index = (current_part - 1) * data_settings['n_words_per_video']
            end_index = start_index + data_settings['n_words_per_video'] - 1
            data_settings['current_part_index_range'] = (start_index, end_index)
            print(f"Processing part {current_part}/{data_settings['n_parts']} with index range {data_settings['current_part_index_range']}")
            df_filt_currentpart = df_filt[
                (df_filt.index >= data_settings['current_part_index_range'][0]) &
                (df_filt.index <= data_settings['current_part_index_range'][1])
            ].reset_index(drop=True)
            df_durations = stitch_audios(audio_settings, data_settings, df_filt_currentpart['chinese'].values.tolist())
            no_hl_img_file_path = draw_vocab_list_whole_image(video_configs, data_settings, df_filt_currentpart)
            create_video_without_highlights(data_settings, video_configs, no_hl_img_file_path)
            create_video_with_highlights(df_durations, audio_settings, data_settings, video_configs)

/Users/scott/Development/my_mandarin_database/utils_shared_hanzi_shorts.py:606: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filtered = df_filtered.replace(data_settings['text_replacements'])

天: 20 words, 2 parts
Processing part 1/2 with index range (0, 9)
Audio duration: 34.7s
MoviePy - Building video output/shared_char_shorts/天/天_no_highlights_part1.mp4.
MoviePy - Writing audio in 天_no_highlights_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/天/天_no_highlights_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/天/天_no_highlights_part1.mp4
MoviePy - Building video output/shared_char_shorts/天/天_part1.mp4.
MoviePy - Writing audio in 天_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/天/天_part1.mp4

frame_index: 100%|█████████▉| 832/834 [00:18<00:00, 45.25it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/天/天_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 832 (out of a total 833 frames), at time 34.67/34.72 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/天/天_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 833 (out of a total 833 frames), at time 34.71/34.72 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/天/天_part1.mp4
Processing part 2/2 with index range (10, 19)
Audio duration: 34.7s
MoviePy - Building video output/shared_char_shorts/天/天_no_highlights_part2.mp4.
MoviePy - Writing audio in 天_no_highlights_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/天/天_no_highlights_part2.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/天/天_no_highlights_part2.mp4
MoviePy - Building video output/shared_char_shorts/天/天_part2.mp4.
MoviePy - Writing audio in 天_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/天/天_part2.mp4

frame_index: 100%|█████████▉| 833/834 [00:18<00:00, 49.16it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/天/天_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 832 (out of a total 833 frames), at time 34.67/34.72 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/天/天_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 833 (out of a total 833 frames), at time 34.71/34.72 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Development/my_mandarin_database/utils_shared_hanzi_shorts.py:606: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filtered = df_filtered.replace(data_settings['text_replacements'])

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/天/天_part2.mp4
金: 18 words, 2 parts
Processing part 1/2 with index range (0, 9)
Audio duration: 33.9s
MoviePy - Building video output/shared_char_shorts/金/金_no_highlights_part1.mp4.
MoviePy - Writing audio in 金_no_highlights_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/金/金_no_highlights_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/金/金_no_highlights_part1.mp4
MoviePy - Building video output/shared_char_shorts/金/金_part1.mp4.
MoviePy - Writing audio in 金_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/金/金_part1.mp4

frame_index: 100%|█████████▉| 815/816 [00:18<00:00, 42.96it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/金/金_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 815 (out of a total 815 frames), at time 33.96/33.99 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/金/金_part1.mp4
Processing part 2/2 with index range (10, 19)
Audio duration: 27.5s
MoviePy - Building video output/shared_char_shorts/金/金_no_highlights_part2.mp4.
MoviePy - Writing audio in 金_no_highlights_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/金/金_no_highlights_part2.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/金/金_no_highlights_part2.mp4
MoviePy - Building video output/shared_char_shorts/金/金_part2.mp4.
MoviePy - Writing audio in 金_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/金/金_part2.mp4

frame_index: 100%|█████████▉| 660/661 [00:13<00:00, 49.58it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/金/金_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 660 (out of a total 660 frames), at time 27.50/27.53 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/金/金_part2.mp4
物: 16 words, 2 parts
Processing part 1/2 with index range (0, 9)
Audio duration: 33.9s
MoviePy - Building video output/shared_char_shorts/物/物_no_highlights_part1.mp4.
MoviePy - Writing audio in 物_no_highlights_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/物/物_no_highlights_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/物/物_no_highlights_part1.mp4
MoviePy - Building video output/shared_char_shorts/物/物_part1.mp4.
MoviePy - Writing audio in 物_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/物/物_part1.mp4

frame_index: 100%|██████████| 816/816 [00:17<00:00, 40.04it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/物/物_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 815 (out of a total 815 frames), at time 33.96/33.99 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/物/物_part1.mp4
Processing part 2/2 with index range (10, 19)
Audio duration: 20.9s
MoviePy - Building video output/shared_char_shorts/物/物_no_highlights_part2.mp4.
MoviePy - Writing audio in 物_no_highlights_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/物/物_no_highlights_part2.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/物/物_no_highlights_part2.mp4
MoviePy - Building video output/shared_char_shorts/物/物_part2.mp4.
MoviePy - Writing audio in 物_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/物/物_part2.mp4

frame_index: 100%|██████████| 504/504 [00:10<00:00, 45.47it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/物/物_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 503 (out of a total 504 frames), at time 20.96/21.00 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Development/my_mandarin_database/utils_shared_hanzi_shorts.py:606: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filtered = df_filtered.replace(data_settings['text_replacements'])

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/物/物_part2.mp4
语: 21 words, 2 parts
Processing part 1/2 with index range (0, 10)
Audio duration: 36.2s
MoviePy - Building video output/shared_char_shorts/语/语_no_highlights_part1.mp4.
MoviePy - Writing audio in 语_no_highlights_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/语/语_no_highlights_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/语/语_no_highlights_part1.mp4
MoviePy - Building video output/shared_char_shorts/语/语_part1.mp4.
MoviePy - Writing audio in 语_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/语/语_part1.mp4

frame_index: 100%|█████████▉| 869/871 [00:18<00:00, 45.71it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/语/语_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 870 (out of a total 870 frames), at time 36.25/36.29 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/语/语_part1.mp4
Processing part 2/2 with index range (11, 21)
Audio duration: 35.3s
MoviePy - Building video output/shared_char_shorts/语/语_no_highlights_part2.mp4.
MoviePy - Writing audio in 语_no_highlights_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/语/语_no_highlights_part2.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/语/语_no_highlights_part2.mp4
MoviePy - Building video output/shared_char_shorts/语/语_part2.mp4.
MoviePy - Writing audio in 语_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/语/语_part2.mp4

frame_index: 100%|█████████▉| 849/850 [00:17<00:00, 49.34it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/语/语_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 849 (out of a total 849 frames), at time 35.38/35.40 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Development/my_mandarin_database/utils_shared_hanzi_shorts.py:606: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filtered = df_filtered.replace(data_settings['text_replacements'])

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/语/语_part2.mp4
时: 24 words, 3 parts
Processing part 1/3 with index range (0, 10)
Audio duration: 37.9s
MoviePy - Building video output/shared_char_shorts/时/时_no_highlights_part1.mp4.
MoviePy - Writing audio in 时_no_highlights_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/时/时_no_highlights_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/时/时_no_highlights_part1.mp4
MoviePy - Building video output/shared_char_shorts/时/时_part1.mp4.
MoviePy - Writing audio in 时_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/时/时_part1.mp4

frame_index: 100%|█████████▉| 907/911 [00:17<00:00, 53.20it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/时/时_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 910 (out of a total 911 frames), at time 37.92/37.96 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/时/时_part1.mp4
Processing part 2/3 with index range (11, 21)
Audio duration: 40.4s
MoviePy - Building video output/shared_char_shorts/时/时_no_highlights_part2.mp4.
MoviePy - Writing audio in 时_no_highlights_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/时/时_no_highlights_part2.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/时/时_no_highlights_part2.mp4
MoviePy - Building video output/shared_char_shorts/时/时_part2.mp4.
MoviePy - Writing audio in 时_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/时/时_part2.mp4

frame_index: 100%|█████████▉| 972/973 [00:18<00:00, 54.15it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/时/时_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 971 (out of a total 972 frames), at time 40.46/40.52 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/时/时_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 972 (out of a total 972 frames), at time 40.50/40.52 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/时/时_part2.mp4
Processing part 3/3 with index range (22, 32)
Audio duration: 8.8s
MoviePy - Building video output/shared_char_shorts/时/时_no_highlights_part3.mp4.
MoviePy - Writing audio in 时_no_highlights_part3TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/时/时_no_highlights_part3.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/时/时_no_highlights_part3.mp4
MoviePy - Building video output/shared_char_shorts/时/时_part3.mp4.
MoviePy - Writing audio in 时_part3TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/时/时_part3.mp4

frame_index:  98%|█████████▊| 208/213 [00:03<00:00, 52.80it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/时/时_no_highlights_part3.mp4, 2764800 bytes wanted but 0 bytes read at frame index 212 (out of a total 213 frames), at time 8.83/8.88 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Development/my_mandarin_database/utils_shared_hanzi_shorts.py:606: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filtered = df_filtered.replace(data_settings['text_replacements'])

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/时/时_part3.mp4
红: 17 words, 2 parts
Processing part 1/2 with index range (0, 9)
Audio duration: 34.5s
MoviePy - Building video output/shared_char_shorts/红/红_no_highlights_part1.mp4.
MoviePy - Writing audio in 红_no_highlights_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/红/红_no_highlights_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/红/红_no_highlights_part1.mp4
MoviePy - Building video output/shared_char_shorts/红/红_part1.mp4.
MoviePy - Writing audio in 红_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/红/红_part1.mp4

frame_index: 100%|█████████▉| 828/830 [00:15<00:00, 56.66it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/红/红_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 828 (out of a total 829 frames), at time 34.50/34.56 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/红/红_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 829 (out of a total 829 frames), at time 34.54/34.56 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/红/红_part1.mp4
Processing part 2/2 with index range (10, 19)
Audio duration: 24.6s
MoviePy - Building video output/shared_char_shorts/红/红_no_highlights_part2.mp4.
MoviePy - Writing audio in 红_no_highlights_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/红/红_no_highlights_part2.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/红/红_no_highlights_part2.mp4
MoviePy - Building video output/shared_char_shorts/红/红_part2.mp4.
MoviePy - Writing audio in 红_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/红/红_part2.mp4

frame_index: 100%|█████████▉| 592/593 [00:10<00:00, 53.36it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/红/红_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 592 (out of a total 592 frames), at time 24.67/24.69 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Development/my_mandarin_database/utils_shared_hanzi_shorts.py:606: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filtered = df_filtered.replace(data_settings['text_replacements'])

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/红/红_part2.mp4
公: 20 words, 2 parts
Processing part 1/2 with index range (0, 9)
Audio duration: 34.5s
MoviePy - Building video output/shared_char_shorts/公/公_no_highlights_part1.mp4.
MoviePy - Writing audio in 公_no_highlights_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/公/公_no_highlights_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/公/公_no_highlights_part1.mp4
MoviePy - Building video output/shared_char_shorts/公/公_part1.mp4.
MoviePy - Writing audio in 公_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/公/公_part1.mp4

frame_index:  99%|█████████▉| 825/830 [00:15<00:00, 45.79it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/公/公_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 828 (out of a total 829 frames), at time 34.50/34.56 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/公/公_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 829 (out of a total 829 frames), at time 34.54/34.56 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/公/公_part1.mp4
Processing part 2/2 with index range (10, 19)
Audio duration: 33.8s
MoviePy - Building video output/shared_char_shorts/公/公_no_highlights_part2.mp4.
MoviePy - Writing audio in 公_no_highlights_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/公/公_no_highlights_part2.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/公/公_no_highlights_part2.mp4
MoviePy - Building video output/shared_char_shorts/公/公_part2.mp4.
MoviePy - Writing audio in 公_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/公/公_part2.mp4

frame_index: 100%|█████████▉| 812/813 [00:16<00:00, 53.20it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/公/公_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 812 (out of a total 813 frames), at time 33.83/33.88 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Development/my_mandarin_database/utils_shared_hanzi_shorts.py:606: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filtered = df_filtered.replace(data_settings['text_replacements'])

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/公/公_part2.mp4
发: 25 words, 3 parts
Processing part 1/3 with index range (0, 9)
Audio duration: 33.1s
MoviePy - Building video output/shared_char_shorts/发/发_no_highlights_part1.mp4.
MoviePy - Writing audio in 发_no_highlights_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/发/发_no_highlights_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/发/发_no_highlights_part1.mp4
MoviePy - Building video output/shared_char_shorts/发/发_part1.mp4.
MoviePy - Writing audio in 发_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/发/发_part1.mp4

frame_index: 100%|█████████▉| 796/797 [00:15<00:00, 52.94it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/发/发_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 796 (out of a total 796 frames), at time 33.17/33.20 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/发/发_part1.mp4
Processing part 2/3 with index range (10, 19)
Audio duration: 34.9s
MoviePy - Building video output/shared_char_shorts/发/发_no_highlights_part2.mp4.
MoviePy - Writing audio in 发_no_highlights_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/发/发_no_highlights_part2.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/发/发_no_highlights_part2.mp4
MoviePy - Building video output/shared_char_shorts/发/发_part2.mp4.
MoviePy - Writing audio in 发_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/发/发_part2.mp4

frame_index:  99%|█████████▉| 834/839 [00:16<00:00, 50.39it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/发/发_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 838 (out of a total 838 frames), at time 34.92/34.93 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/发/发_part2.mp4
Processing part 3/3 with index range (20, 29)
Audio duration: 18.2s
MoviePy - Building video output/shared_char_shorts/发/发_no_highlights_part3.mp4.
MoviePy - Writing audio in 发_no_highlights_part3TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/发/发_no_highlights_part3.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/发/发_no_highlights_part3.mp4
MoviePy - Building video output/shared_char_shorts/发/发_part3.mp4.
MoviePy - Writing audio in 发_part3TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/发/发_part3.mp4

frame_index: 100%|█████████▉| 438/439 [00:08<00:00, 54.28it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/发/发_no_highlights_part3.mp4, 2764800 bytes wanted but 0 bytes read at frame index 438 (out of a total 439 frames), at time 18.25/18.31 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Development/my_mandarin_database/utils_shared_hanzi_shorts.py:606: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filtered = df_filtered.replace(data_settings['text_replacements'])

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/发/发_part3.mp4
自: 22 words, 2 parts
Processing part 1/2 with index range (0, 10)
Audio duration: 36.6s
MoviePy - Building video output/shared_char_shorts/自/自_no_highlights_part1.mp4.
MoviePy - Writing audio in 自_no_highlights_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/自/自_no_highlights_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/自/自_no_highlights_part1.mp4
MoviePy - Building video output/shared_char_shorts/自/自_part1.mp4.
MoviePy - Writing audio in 自_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/自/自_part1.mp4

frame_index:  99%|█████████▉| 874/879 [00:16<00:00, 55.03it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/自/自_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 878 (out of a total 878 frames), at time 36.58/36.62 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/自/自_part1.mp4
Processing part 2/2 with index range (11, 21)
Audio duration: 40.0s
MoviePy - Building video output/shared_char_shorts/自/自_no_highlights_part2.mp4.
MoviePy - Writing audio in 自_no_highlights_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/自/自_no_highlights_part2.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/自/自_no_highlights_part2.mp4
MoviePy - Building video output/shared_char_shorts/自/自_part2.mp4.
MoviePy - Writing audio in 自_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/自/自_part2.mp4

frame_index: 100%|██████████| 961/961 [00:17<00:00, 56.97it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/自/自_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 960 (out of a total 960 frames), at time 40.00/40.02 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Development/my_mandarin_database/utils_shared_hanzi_shorts.py:606: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filtered = df_filtered.replace(data_settings['text_replacements'])

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/自/自_part2.mp4
一: 23 words, 2 parts
Processing part 1/2 with index range (0, 11)
Audio duration: 39.4s
MoviePy - Building video output/shared_char_shorts/一/一_no_highlights_part1.mp4.
MoviePy - Writing audio in 一_no_highlights_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/一/一_no_highlights_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/一/一_no_highlights_part1.mp4
MoviePy - Building video output/shared_char_shorts/一/一_part1.mp4.
MoviePy - Writing audio in 一_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/一/一_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/一/一_part1.mp4
Processing part 2/2 with index range (12, 23)
Audio duration: 40.4s
MoviePy - Building video output/shared_char_shorts/一/一_no_highlights_part2.mp4.
MoviePy - Writing audio in 一_no_highlights_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/一/一_no_highlights_part2.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/一/一_no_highlights_part2.mp4
MoviePy - Building video output/shared_char_shorts/一/一_part2.mp4.
MoviePy - Writing audio in 一_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/一/一_part2.mp4

frame_index: 100%|█████████▉| 968/972 [00:18<00:00, 48.11it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/一/一_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 971 (out of a total 971 frames), at time 40.46/40.46 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/一/一_part2.mp4
山: 8 words, 1 parts
Processing part 1/1 with index range (0, 9)
Audio duration: 28.5s
MoviePy - Building video output/shared_char_shorts/山/山_no_highlights_part1.mp4.
MoviePy - Writing audio in 山_no_highlights_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/山/山_no_highlights_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/山/山_no_highlights_part1.mp4
MoviePy - Building video output/shared_char_shorts/山/山_part1.mp4.
MoviePy - Writing audio in 山_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/山/山_part1.mp4

frame_index:  99%|█████████▉| 681/686 [00:12<00:00, 56.77it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/山/山_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 685 (out of a total 685 frames), at time 28.54/28.58 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Development/my_mandarin_database/utils_shared_hanzi_shorts.py:606: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filtered = df_filtered.replace(data_settings['text_replacements'])

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/山/山_part1.mp4
头: 23 words, 2 parts
Processing part 1/2 with index range (0, 11)
Audio duration: 40.2s
MoviePy - Building video output/shared_char_shorts/头/头_no_highlights_part1.mp4.
MoviePy - Writing audio in 头_no_highlights_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/头/头_no_highlights_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/头/头_no_highlights_part1.mp4
MoviePy - Building video output/shared_char_shorts/头/头_part1.mp4.
MoviePy - Writing audio in 头_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/头/头_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/头/头_part1.mp4
Processing part 2/2 with index range (12, 23)
Audio duration: 37.4s
MoviePy - Building video output/shared_char_shorts/头/头_no_highlights_part2.mp4.
MoviePy - Writing audio in 头_no_highlights_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/头/头_no_highlights_part2.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/头/头_no_highlights_part2.mp4
MoviePy - Building video output/shared_char_shorts/头/头_part2.mp4.
MoviePy - Writing audio in 头_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/头/头_part2.mp4

frame_index: 100%|█████████▉| 896/899 [00:17<00:00, 38.90it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/头/头_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 898 (out of a total 898 frames), at time 37.42/37.43 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Development/my_mandarin_database/utils_shared_hanzi_shorts.py:606: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filtered = df_filtered.replace(data_settings['text_replacements'])

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/头/头_part2.mp4
花: 26 words, 3 parts
Processing part 1/3 with index range (0, 9)
Audio duration: 34.3s
MoviePy - Building video output/shared_char_shorts/花/花_no_highlights_part1.mp4.
MoviePy - Writing audio in 花_no_highlights_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/花/花_no_highlights_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/花/花_no_highlights_part1.mp4
MoviePy - Building video output/shared_char_shorts/花/花_part1.mp4.
MoviePy - Writing audio in 花_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/花/花_part1.mp4

frame_index:  99%|█████████▉| 821/826 [00:15<00:00, 54.01it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/花/花_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 825 (out of a total 825 frames), at time 34.38/34.40 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/花/花_part1.mp4
Processing part 2/3 with index range (10, 19)
Audio duration: 34.3s
MoviePy - Building video output/shared_char_shorts/花/花_no_highlights_part2.mp4.
MoviePy - Writing audio in 花_no_highlights_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/花/花_no_highlights_part2.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/花/花_no_highlights_part2.mp4
MoviePy - Building video output/shared_char_shorts/花/花_part2.mp4.
MoviePy - Writing audio in 花_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/花/花_part2.mp4

frame_index: 100%|█████████▉| 823/825 [00:15<00:00, 54.24it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/花/花_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 824 (out of a total 824 frames), at time 34.33/34.35 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/花/花_part2.mp4
Processing part 3/3 with index range (20, 29)
Audio duration: 20.6s
MoviePy - Building video output/shared_char_shorts/花/花_no_highlights_part3.mp4.
MoviePy - Writing audio in 花_no_highlights_part3TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/花/花_no_highlights_part3.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/花/花_no_highlights_part3.mp4
MoviePy - Building video output/shared_char_shorts/花/花_part3.mp4.
MoviePy - Writing audio in 花_part3TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/花/花_part3.mp4

/Users/scott/Development/my_mandarin_database/utils_shared_hanzi_shorts.py:606: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filtered = df_filtered.replace(data_settings['text_replacements'])

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/花/花_part3.mp4
外: 26 words, 3 parts
Processing part 1/3 with index range (0, 9)
Audio duration: 32.1s
MoviePy - Building video output/shared_char_shorts/外/外_no_highlights_part1.mp4.
MoviePy - Writing audio in 外_no_highlights_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/外/外_no_highlights_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/外/外_no_highlights_part1.mp4
MoviePy - Building video output/shared_char_shorts/外/外_part1.mp4.
MoviePy - Writing audio in 外_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/外/外_part1.mp4

frame_index: 100%|█████████▉| 770/772 [00:14<00:00, 55.03it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/外/外_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 771 (out of a total 771 frames), at time 32.12/32.16 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/外/外_part1.mp4
Processing part 2/3 with index range (10, 19)
Audio duration: 34.0s
MoviePy - Building video output/shared_char_shorts/外/外_no_highlights_part2.mp4.
MoviePy - Writing audio in 外_no_highlights_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/外/外_no_highlights_part2.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/外/外_no_highlights_part2.mp4
MoviePy - Building video output/shared_char_shorts/外/外_part2.mp4.
MoviePy - Writing audio in 外_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/外/外_part2.mp4

frame_index: 100%|██████████| 818/818 [00:15<00:00, 53.32it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/外/外_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 817 (out of a total 817 frames), at time 34.04/34.06 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/外/外_part2.mp4
Processing part 3/3 with index range (20, 29)
Audio duration: 20.0s
MoviePy - Building video output/shared_char_shorts/外/外_no_highlights_part3.mp4.
MoviePy - Writing audio in 外_no_highlights_part3TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/外/外_no_highlights_part3.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/外/外_no_highlights_part3.mp4
MoviePy - Building video output/shared_char_shorts/外/外_part3.mp4.
MoviePy - Writing audio in 外_part3TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/外/外_part3.mp4

frame_index: 100%|█████████▉| 479/481 [00:09<00:00, 53.06it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/外/外_no_highlights_part3.mp4, 2764800 bytes wanted but 0 bytes read at frame index 480 (out of a total 481 frames), at time 20.00/20.06 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Development/my_mandarin_database/utils_shared_hanzi_shorts.py:606: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filtered = df_filtered.replace(data_settings['text_replacements'])

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/外/外_part3.mp4
手: 32 words, 3 parts
Processing part 1/3 with index range (0, 10)
Audio duration: 37.2s
MoviePy - Building video output/shared_char_shorts/手/手_no_highlights_part1.mp4.
MoviePy - Writing audio in 手_no_highlights_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/手/手_no_highlights_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/手/手_no_highlights_part1.mp4
MoviePy - Building video output/shared_char_shorts/手/手_part1.mp4.
MoviePy - Writing audio in 手_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/手/手_part1.mp4

frame_index: 100%|██████████| 896/896 [00:16<00:00, 58.29it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/手/手_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 895 (out of a total 895 frames), at time 37.29/37.30 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/手/手_part1.mp4
Processing part 2/3 with index range (11, 21)
Audio duration: 37.9s
MoviePy - Building video output/shared_char_shorts/手/手_no_highlights_part2.mp4.
MoviePy - Writing audio in 手_no_highlights_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/手/手_no_highlights_part2.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/手/手_no_highlights_part2.mp4
MoviePy - Building video output/shared_char_shorts/手/手_part2.mp4.
MoviePy - Writing audio in 手_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/手/手_part2.mp4

frame_index:  99%|█████████▉| 906/911 [00:16<00:00, 56.45it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/手/手_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 910 (out of a total 910 frames), at time 37.92/37.93 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/手/手_part2.mp4
Processing part 3/3 with index range (22, 32)
Audio duration: 35.6s
MoviePy - Building video output/shared_char_shorts/手/手_no_highlights_part3.mp4.
MoviePy - Writing audio in 手_no_highlights_part3TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/手/手_no_highlights_part3.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/手/手_no_highlights_part3.mp4
MoviePy - Building video output/shared_char_shorts/手/手_part3.mp4.
MoviePy - Writing audio in 手_part3TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/手/手_part3.mp4

frame_index:  99%|█████████▉| 851/856 [00:15<00:00, 56.96it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/手/手_no_highlights_part3.mp4, 2764800 bytes wanted but 0 bytes read at frame index 855 (out of a total 855 frames), at time 35.62/35.66 sec. Using the last valid frame instead.
  warnings.warn(
/Users/scott/Development/my_mandarin_database/utils_shared_hanzi_shorts.py:606: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filtered = df_filtered.replace(data_settings['text_replacements'])

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/手/手_part3.mp4
生: 24 words, 2 parts
Processing part 1/2 with index range (0, 11)
Audio duration: 43.1s
MoviePy - Building video output/shared_char_shorts/生/生_no_highlights_part1.mp4.
MoviePy - Writing audio in 生_no_highlights_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/生/生_no_highlights_part1.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/生/生_no_highlights_part1.mp4
MoviePy - Building video output/shared_char_shorts/生/生_part1.mp4.
MoviePy - Writing audio in 生_part1TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/生/生_part1.mp4

frame_index: 100%|█████████▉| 1032/1037 [00:18<00:00, 55.98it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/生/生_no_highlights_part1.mp4, 2764800 bytes wanted but 0 bytes read at frame index 1036 (out of a total 1036 frames), at time 43.17/43.18 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/生/生_part1.mp4
Processing part 2/2 with index range (12, 23)
Audio duration: 43.4s
MoviePy - Building video output/shared_char_shorts/生/生_no_highlights_part2.mp4.
MoviePy - Writing audio in 生_no_highlights_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/生/生_no_highlights_part2.mp4

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/生/生_no_highlights_part2.mp4
MoviePy - Building video output/shared_char_shorts/生/生_part2.mp4.
MoviePy - Writing audio in 生_part2TEMP_MPY_wvf_snd.mp3

MoviePy - Done.
MoviePy - Writing video output/shared_char_shorts/生/生_part2.mp4

frame_index: 100%|█████████▉| 1044/1045 [00:18<00:00, 58.23it/s, now=None]/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/moviepy/video/io/ffmpeg_reader.py:190: UserWarning: In file output/shared_char_shorts/生/生_no_highlights_part2.mp4, 2764800 bytes wanted but 0 bytes read at frame index 1044 (out of a total 1044 frames), at time 43.50/43.52 sec. Using the last valid frame instead.
  warnings.warn(

MoviePy - Done !
MoviePy - video ready output/shared_char_shorts/生/生_part2.mp4

In [5]:
data_settings = data_settings_by_char[chosen_char]
data_settings = enhance_data_settings(data_settings)
create_directories(data_settings)
data_settings

{'shared_char': '生',
 'char_pinyin': 'shēng',
 'char_english': 'life',
 'max_priority': 6,
 'min_adu': 3,
 'min_per': 3,
 'types_allowed': ['word',
  'prefix',
  'suffix',
  'abbreviation',
  'multi_word',
  'verb_ending',
  'proper noun'],
 'sort_cols': ['priority', 'cat_v3', 'pinyin'],
 'sort_ascending': [True, True, True],
 'words_rmv': ['花生酱',
  '轻奢生活',
  '生育率',
  '独生女',
  '独生子',
  '博士生导师',
  '咖啡生产地',
  '出生率',
  '低生育率',
  '招生',
  '精神卫生科',
  '生效',
  '生产者名称'],
 'n_words_per_video': 12,
 'current_part': 1,
 'text_replacements': {'to produce;production': 'production',
  'lifestyle;way of life': 'lifestyle',
  'business (how doing)': 'business',
  'physiological;physical': 'physiological'},
 'output_path_base': 'output/shared_char_shorts/',
 'output_path': 'output/shared_char_shorts/生',
 'output_path_audio': 'output/shared_char_shorts/生/audio_files',
 'output_path_images': 'output/shared_char_shorts/生/images'}

# Load data

In [7]:
previous_video_chars = ['口', '电', '车', '色', '子', '海'] + list(data_settings_by_char.keys())
df_character_appearances = get_character_counts(df_all_vocab, data_settings)
df_character_appearances = df_character_appearances[~df_character_appearances['character'].isin(previous_video_chars)]
print(len(df_all_vocab), len(df_character_appearances))
df_character_appearances['character'].value_counts().head(30)

7669 11170

character
大    80
人    80
机    48
科    48
心    45
不    39
中    38
家    37
小    37
国    36
自    36
时    33
发    33
学    31
公    31
红    31
的    30
平    30
语    30
物    30
金    29
天    29
西    29
上    29
行    29
气    29
猫    29
体    28
可    28
点    28
Name: count, dtype: int64

In [20]:
data_settings['shared_char'] = '天'
df_filt = get_filtered_words(df_all_vocab, data_settings)
print([data_settings['shared_char']] + df_filt['chinese'].values.tolist())
print({k:k for k in df_filt['english'].values.tolist()})
print(len(df_filt))
df_filt.head(40)

['天', '天气预报', '天堂', '白天', '第二天', '平均每天', '这几天', '天空', '天安门广场', '天花板', '天桥', '天才', '天真', '摩天轮', '天猫', '天津', '天鹅', '天文', '摩天楼', '天线', '天然', '天然气', '天妇罗', '先天', '天坛', '天蓝', '天主教', '天平', '天津市', '天王星']
{'weather forecast': 'weather forecast', 'heaven;paradise': 'heaven;paradise', 'daytime': 'daytime', 'the next day': 'the next day', 'Average daily': 'Average daily', 'These days': 'These days', 'sky': 'sky', 'Tiananmen Square': 'Tiananmen Square', 'ceiling': 'ceiling', 'pedestrian bridge': 'pedestrian bridge', 'genius': 'genius', 'innocent;naive': 'innocent;naive', 'ferris wheel': 'ferris wheel', 'Chinese Amazon (less variety)': 'Chinese Amazon (less variety)', 'Tianjin': 'Tianjin', 'swan': 'swan', 'astronomy': 'astronomy', 'skyscraper': 'skyscraper', 'antenna': 'antenna', 'natural': 'natural', 'natural gas': 'natural gas', 'tempura': 'tempura', 'innate': 'innate', 'Temple of Heaven (Beijing), historic site for imperial ceremonies': 'Temple of Heaven (Beijing), historic site for imperial ceremonies', 'sky blue': 'sky blue', 'Catholicism': 'Catholicism', 'balance scale': 'balance scale', 'Tianjin Municipality': 'Tianjin Municipality', 'Uranus': 'Uranus'}
29

/Users/scott/Development/my_mandarin_database/utils_shared_hanzi_shorts.py:567: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  'fill': video_configs['words_settings']['fill']['english'],

,id,chinese,pinyin,english,type,priority,category1,category2,cat_v3,cat2_v3,cat3_v3,hsk_level,known,known_pinyin_prompt,known_english_prompt,quality,word1,word1_english,word2,word2_english,word3,word3_english,word4,word4_english,voice_zh,voice_en,video_notes,sentence,sentence_pinyin,sentence_english,date,source1,source2,funny,per,adu,slang,phonetic
0,782,天气预报,tiān qì yù bào,weather forecast,multi_word,1,travel,NaN,Weather & Nature,NaN,天气现象,MISSING,4.0,2.0,2.0,3.0,天气,weather,预期,to expect,报,report,NaN,NaN,NaN,NaN,NaN,我看了今天的天气预报,Wǒ kàn le jīntiān de tiānqì yùbào,I checked today's weather forecast,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
1,1040,天堂,tiān táng,heaven;paradise,word,2,general,NaN,Culture & Society,NaN,宗教与信仰,6.0,2.0,1.0,2.0,2.0,天,sky,堂,hall,NaN,NaN,NaN,NaN,NaN,NaN,NaN,他觉得海边是天堂,Tā juéde hǎibiān shì tiāntáng,He thinks the beach is paradise,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
2,2,白天,bái tiān,daytime,word,2,time,NaN,Time,NaN,时间段 / 时长,1.0,2.0,1.0,1.0,1.0,白,white,天,day,NaN,NaN,NaN,NaN,NaN,NaN,NaN,白天很热晚上比较凉快,Báitiān hěn rè wǎnshàng bǐjiào liángkuai,It is hot in the daytime and cooler at night,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
3,3738,第二天,dì èr tiān,the next day,multi_word,2,time,NaN,Time,NaN,时间顺序与先后,MISSING,2.0,1.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我们第二天再出发,Wǒmen dì èr tiān zài chūfā,We will set out the next day,2025-06-08,daily add,NaN,NaN,5.0,5.0,5.0,NaN
4,3389,平均每天,píng jūn měi tiān,Average daily,multi_word,2,amount,degree,Time,NaN,频率与习惯,MISSING,2.0,1.0,5.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我平均每天跑步三公里,Wǒ píngjūn měitiān pǎobù sān gōnglǐ,I run three kilometers every day on average,2025-02-10,ltl,NaN,NaN,5.0,5.0,5.0,NaN
5,3326,这几天,zhè jǐ tiān,These days,multi_word,2,time,NaN,Time,NaN,现在与当前,MISSING,3.0,2.0,5.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这几天很忙,Zhè jǐ tiān hěn máng,These past few days have been busy,2025-02-10,ltl,NaN,NaN,5.0,5.0,5.0,NaN
6,5928,天空,tiān kōng,sky,word,2,NaN,NaN,Weather & Nature,NaN,天体与天空现象,3.0,5.0,5.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,今天的天空很蓝,jīn tiān de tiān kōng hěn lán,The sky is very blue today,2025-11-04,codenames,NaN,NaN,5.0,5.0,5.0,NaN
7,6795,天安门广场,tiān ān mén guǎng chǎng,Tiananmen Square,proper noun,2,NaN,NaN,my_china_spots,NaN,NaN,MISSING,5.0,5.0,5.0,4.0,天空,sky,安全,safe,门口,gate,广场,square,NaN,NaN,NaN,清晨的天安门广场非常庄严。,qīng chén de tiān ān mén guǎng chǎng fēi cháng...,Tiananmen Square is very solemn in the early m...,2025-12-30,china places,NaN,NaN,5.0,5.0,5.0,NaN
8,5605,天花板,tiān huā bǎn,ceiling,word,3,house,NaN,Architecture & Infrastructure,NaN,NaN,MISSING,5.0,5.0,5.0,2.0,天,sky,花,flower,板,board,NaN,NaN,NaN,NaN,NaN,房间的天花板上装着漂亮的灯,fáng jiān de tiān huā bǎn shàng zhuāng zhe pià...,A beautiful lamp is installed on the ceiling,2025-10-24,daily add,NaN,NaN,5.0,5.0,5.0,NaN
9,6117,天桥,tiān qiáo,pedestrian bridge,word,3,NaN,NaN,Architecture & Infrastructure,NaN,NaN,MISSING,5.0,5.0,5.0,4.0,天空,sky,桥,bridge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我们在天桥上等你,wǒ men zài tiān qiáo shàng děng nǐ,We’ll wait for you on the pedestrian bridge,2025-11-11,daily add,NaN,NaN,5.0,5.0,5.0,NaN
10,1004,天才,tiān cái,genius,word,3,characteristic,Skills & Abilities,Emotions & Relationships,NaN,社会标签,5.0,4.0,2.0,2.0,2.0,天,god,才能,talent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,她是个音乐天才,Tā shì gè yīnyuè tiāncái,She is a musical genius,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
11,34,天真,tiān zhēn,innocent;naive,word,3,characteristic,Negative Traits/Qualities,Emotions & Relationships,NaN,性格特质,4.0,5.0,2.0,2.0,2.0,天,God,真,true,NaN,NaN,NaN,NaN,NaN,NaN,NaN,她很天真可爱,Tā hěn tiānzhēn kě’ài,She is very innocent and cute,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
12,6343,摩天轮,mó tiān lún,ferris wheel,word,3,NaN,NaN,Entertainment,NaN,娱乐与休闲场所,MISSING,5.0,5.0,5.0,2.0,摩擦,to rub,天空,sky,轮,wheel,NaN,NaN,NaN,NaN,NaN,夜景下的摩天轮特别漂亮,yè jǐng xià de mó tiān lún tè bié piào liang,The ferris wheel looks beautiful at night,2025-12-12,daily add,NaN,NaN,5.0,5.0,5.0,NaN
13,5303,天猫,tiān māo,Chinese Amazon (less variety),proper noun,3,electronics,app,Technology & Internet,app name,电商与本地生活平台,MISSING,5.0,5.0,2.0,4.0,天,sky,猫,cat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,他在天猫买了一双运动鞋,tā zài tiānmāo mǎile yìshuāng yùndòng...,He bought a pair of sneakers on Tmall,2025-09-27,daily add,NaN,NaN,5.0,5.0,5.0,NaN
14,6126,天津,Tiānjīn,Tianjin,proper noun,3,NaN,NaN,Travel & Geography,china_cities,中国直辖市,MISSING,5.0,5.0,1.0,6.0,天,sky,津,(uncommon),NaN,NaN,NaN,NaN,NaN,NaN,Tianjin Municipality (天津),天津有著名的古文化街,Tiānjīn yǒu zhù míng de gǔ wén huà jiē,Tianjin has the famous Ancient Culture Street,2025-11-11,China cities,NaN,NaN,5.0,5.0,5.0,NaN
15,1418,天鹅,tiān 'é,swan,word,4,animal,bird,Animals,NaN,鸟类,MISSING,5.0,5.0,5.0,1.0,天,sky,鹅,goose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,湖里有几只白天鹅,hú lǐ yǒu jǐ zhī bái tiān é,there are several white swans in the lake,2025-06-15,NaN,NaN,NaN,5.0,5.0,5.0,NaN
16,763,天文,tiān wén,astronomy,word,4,career,Academia & Research,Education & Learning,NaN,学科领域,5.0,5.0,1.0,5.0,1.0,天,sky,文,arts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我喜欢天文,Wǒ xǐhuān tiānwén,I like astronomy,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
17,5854,摩天楼,mó tiān lóu,skyscraper,word,5,NaN,NaN,Architecture & Infrastructure,NaN,NaN,MISSING,5.0,5.0,5.0,3.0,摩,to rub,天空,sky,大楼,building,NaN,NaN,NaN,NaN,NaN,那座摩天楼高得看不见顶,nà zuò mó tiān lóu gāo de kàn bú jiàn dǐng,That skyscraper is so tall you can’t see the top,2025-11-04,codenames,NaN,NaN,5.0,5.0,5.0,NaN
18,1199,天线,tiān xiàn,antenna,word,5,electronics,Devices & Hardware,Devices & Electronics,NaN,电力与电子元件,MISSING,5.0,5.0,5.0,1.0,天,sky,线,thread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,屋顶上有一根天线,wūdǐng shàng yǒu yī gēn tiānxiàn,there is an antenna on the roof,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
19,305,天然,tiān rán,natural,word,5,outdoor,NaN,Environment,NaN,抽象描述与评价,6.0,5.0,2.0,5.0,2.0,天,today,当然,of course,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这些矿泉水是天然的,zhè xiē kuàng quán shuǐ shì tiān rán de,this mineral water is natural,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
20,7047,天然气,tiān rán qì,natural gas,word,5,NaN,NaN,Environment,NaN,能源与资源,5.0,5.0,5.0,5.0,4.0,天然,natural,气体,gas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,很多家庭用天然气做饭。,hěn duō jiā tíng yòng tiān rán qì zuò fàn.,many households use natural gas to cook.,2026-01-19,anomia_examples,NaN,NaN,5.0,5.0,5.0,NaN
21,5710,天妇罗,tiān fù luó,tempura,word,5,food,NaN,Food & Drink,NaN,油炸食品,MISSING,5.0,5.0,5.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这家餐厅的天妇罗很地道,zhè jiā cān tīng de tiān fù luó hěn dì dào,The tempura in this restaurant is authentic,2025-10-30,daily add,NaN,NaN,5.0,5.0,5.0,1.0
22,3852,先天,xiān tiān,innate,word,5,people,NaN,Health & Body,NaN,遗传与发育,MISSING,5.0,5.0,5.0,2.0,先,first,天,day,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这是先天的缺陷,zhè shì xiāntiān de quēxiàn,this is a congenital defect,2025-07-07,daily add,NaN,NaN,5.0,5.0,5.0,NaN
23,6797,天坛,tiān tán,"Temple of Heaven (Beijing), historic site for ...",proper noun,5,NaN,NaN,my_china_spots,NaN,NaN,MISSING,5.0,5.0,5.0,4.0,天堂,heaven,坛,altar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,天坛是古代皇帝祭天的地方。,tiān tán shì gǔ dài huáng dì jì tiān de dì fang,The Temple of Heaven was where emperors worshi...,2025-12-30,china places,NaN,NaN,5.0,5.0,5.0,NaN
24,6644,天蓝,tiān lán,sky blue,word,5,NaN,NaN,my_colors,NaN,NaN,MISSING,5.0,5.0,5.0,4.0,天空,sky,蓝色,blue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,天蓝色让人心情平静,tiān lán sè ràng rén xīn qíng píng jìng,Sky blue calms people,2025-12-24,color vocab,NaN,NaN,5.0,5.0,5.0,NaN
25,4370,天主教,tiān zhǔ jiào,Catholicism,proper noun,6,society,NaN,Culture & Society,NaN,宗教与信仰,MISSING,5.0,5.0,5.0,2.0,天,God,主,master,宗教,religion,NaN,NaN,NaN,NaN,NaN,他信仰天主教,Tā xìnyǎng Tiānzhǔjiào,He practices Catholicism,2025-08-12,daily add,NaN,NaN,5.0,5.0,5.0,NaN
26,7448,天平,tiān píng,balance scale,word,6,NaN,NaN,Devices & Electronics,NaN,测量与科学仪器,MISSING,5.0,5.0,5.0,3.0,天空,sky,平衡,balance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,实验室里有天平。,shí yàn shì lǐ yǒu tiān píng.,there is a balance scale in the lab.,2026-01-19,anomia_examples,NaN,NaN,5.0,5.0,5.0,NaN
27,6222,天津市,tiān jīn shì,Tianjin Municipality,proper noun,6,NaN,NaN,Travel & Geography,china_provinces,中国直辖市,MISSING,5.0,5.0,5.0,5.0,天,sky,津,(uncommon),市,city,NaN,NaN,NaN,NaN,NaN,天津靠近北京。,tiān jīn kào jìn běi jīng,Tianjin is close to Beijing.,2025-11-12,China provinces,NaN,NaN,5.0,5.0,5.0,NaN
28,7436,天王星,tiān wáng xīng,Uranus,proper noun,6,NaN,NaN,Travel & Geography,NaN,宇宙与天体,MISSING,5.0,5.0,5.0,2.0,天空,sky,王,king,星,star,NaN,NaN,NaN,NaN,NaN,天王星自转独特。,tiān wáng xīng zì zhuǎn dú tè.,uranus rotates uniquely.,2026-01-19,anomia_examples,NaN,NaN,5.0,5.0,5.0,NaN

# Create video for each part

In [9]:
print('Cut vocab into parts')
data_settings['n_words_total'] = len(df_filt)
data_settings['n_parts'] = int(np.ceil(len(df_filt) / data_settings['n_words_per_video']))

for current_part in range(1, data_settings['n_parts'] + 1):
    # Determine vocabulary in current part
    data_settings['current_part'] = current_part
    start_index = (current_part - 1) * data_settings['n_words_per_video']
    end_index = start_index + data_settings['n_words_per_video'] - 1
    data_settings['current_part_index_range'] = (start_index, end_index)
    print(f"Processing part {current_part}/{data_settings['n_parts']} with index range {data_settings['current_part_index_range']}")
    df_filt_currentpart = df_filt[
        (df_filt.index >= data_settings['current_part_index_range'][0]) &
        (df_filt.index <= data_settings['current_part_index_range'][1])
    ].reset_index(drop=True)

    print('Making audio')
    df_durations = stitch_audios(audio_settings, data_settings, df_filt_currentpart['chinese'].values.tolist())
    print('Making image')
    no_hl_img_file_path = draw_vocab_list_whole_image(video_configs, data_settings, df_filt_currentpart)
    print('Making video without highlights')
    create_video_without_highlights(data_settings, video_configs, no_hl_img_file_path)
    print('Making video with highlights')
    create_video_with_highlights(df_durations, audio_settings, data_settings, video_configs)

Cut vocab into parts
Processing part 1/2 with index range (0, 11)
Making audio

/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/pydub/utils.py:300: SyntaxWarning: invalid escape sequence '\('
  m = re.match('([su]([0-9]{1,2})p?) \(([0-9]{1,2}) bit\)$', token)
/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/pydub/utils.py:301: SyntaxWarning: invalid escape sequence '\('
  m2 = re.match('([su]([0-9]{1,2})p?)( \(default\))?$', token)
/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/pydub/utils.py:310: SyntaxWarning: invalid escape sequence '\('
  elif re.match('(flt)p?( \(default\))?$', token):
/Users/scott/Library/Caches/pypoetry/virtualenvs/my-mandarin-database-XyoBA6Fv-py3.13/lib/python3.13/site-packages/pydub/utils.py:314: SyntaxWarning: invalid escape sequence '\('
  elif re.match('(dbl)p?( \(default\))?$', token):

FileNotFoundError: [Errno 2] No such file or directory: 'output/shared_char_shorts/生/audio_files/生.mp3'