In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import time
import numpy as np
import os
import pandas as pd
from collections import defaultdict
from constants import WORD_TYPES, PROPER_NOUN_TYPES
pd.options.display.max_columns = 100
pd.options.display.max_rows = 130

In [3]:
from utils_shared_hanzi_shorts import (
    load_video_configs, draw_vocab_list_whole_image, 
    create_video_with_highlights, create_video_without_highlights
)
from utils_data import (load_raw_data, check_dups)

# Settings

In [ ]:
audio_settings = {
    'voice_name_zh': 'zh-CN-XiaoxiaoNeural',
    'audio_plan': 'c2word',
    'pause_ms_beginning': 150,
    'pause_ms_within_word': 200,
    'pause_ms_between': 500,
}

data_settings = {
    'current_hsk_level': '3.0',
    'priority_limit': 1,
    'sort_cols': ['cat_v3', 'cat3_v3', 'pinyin'],
    'sort_ascending': [True, True, True],
    'words_rmv': ['父亲', '母亲'],
    'output_path': 'output/hsk_top_shorts/',
    'output_path_audio': 'output/hsk_top_shorts/audio/',
    'output_path_images': 'output/hsk_top_shorts/images/',
    'n_words_per_video': 10,
}

video_configs = load_video_configs()
video_configs['words_settings'] = {
    'x': {'chinese': 50, 'pinyin': 165, 'english': 420},
    'max_line_length_buffer_size': {'chinese': 10, 'pinyin': 20, 'english': 60},
    'max_line_length': {},
    'y_gap': 42,
    'spacing': 50,
    'font_size': {'chinese': 36, 'pinyin': 36, 'english': 36},
    'align': {'chinese': 'left', 'pinyin': 'left', 'english': 'left'},
    'fill': {'chinese': '#000000', 'pinyin': '#000000', 'english': '#000000'},
}
video_configs['words_settings']['y'] = video_configs['horizontal_line']['y'] + \
    video_configs['words_settings']['y_gap']
video_configs['words_settings']['max_line_length']['chinese'] = video_configs['words_settings']['x']['pinyin'] - video_configs['words_settings']['x']['chinese'] - video_configs['words_settings']['max_line_length_buffer_size']['chinese']
video_configs['words_settings']['max_line_length']['pinyin'] = video_configs['words_settings']['x']['english'] - video_configs['words_settings']['x']['pinyin'] - video_configs['words_settings']['max_line_length_buffer_size']['pinyin']
video_configs['words_settings']['max_line_length']['english'] = video_configs['bg_size'][0] - video_configs['words_settings']['x']['english'] - video_configs['words_settings']['max_line_length_buffer_size']['english']

video_configs['title_format'] = 'english_only'
video_configs['title_text_settings'] = {
    'text': f"HSK{data_settings['current_hsk_level'][0]}\ntop words",
    'font_path': video_configs['font_path'],
    'font_size': 50,
    'y': 50,
    'spacing': 20,
    'align': 'center',
    'fill': 'black',
    'max_line_length': video_configs['bg_size'][0] - (2 * 50),
}
data_settings['shared_char'] = f"hsk{data_settings['current_hsk_level'][0]}"

# Load data

In [70]:
truly_load_data = False
df_all_vocab = load_raw_data(truly_load_data=truly_load_data)
df_dups = check_dups(df_all_vocab)
print(df_all_vocab.shape)
print(f'# duplicate vocab: {len(df_dups)}')
df_all_vocab.head(3)

!!!!!!!! WARNING: not truly loading data !!!!!!!!
(7600, 38)
# duplicate vocab: 0

,id,chinese,pinyin,english,type,priority,category1,category2,cat_v3,cat2_v3,cat3_v3,hsk_level,known,known_pinyin_prompt,known_english_prompt,quality,word1,word1_english,word2,word2_english,word3,word3_english,word4,word4_english,voice_zh,voice_en,video_notes,sentence,sentence_pinyin,sentence_english,date,source1,source2,funny,per,adu,slang,phonetic
0,152,意见,yì jiàn,opinion,word,1,people,NaN,Language & Expression,NaN,观点与立场,2.0,4.0,2.0,5.0,2.0,意思,meaning,见,to see,NaN,NaN,NaN,NaN,NaN,NaN,NaN,大家都提出了不同意见,Dàjiā dōu tíchū le bùtóng yìjiàn,Everyone gave different opinions,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
1,407,相机,xiàng jī,camera,word,1,hobbies,NaN,Devices & Electronics,NaN,摄影与光学设备,2.0,5.0,2.0,5.0,3.0,相信,to believe,机,machine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我带了相机拍照,Wǒ dài le xiàngjī pāizhào,I brought a camera to take photos,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
2,749,机会,jī huì,opportunity;chance,word,1,career,Other,Education & Learning,NaN,结果与影响,2.0,2.0,1.0,5.0,3.0,机,machine,会,to be able to,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这次机会很难得,Zhè cì jīhuì hěn nándé,This is a rare opportunity,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN

In [71]:
# # Most important HSK1
# current_hsk_level = 6
# df_this_hsk = df_all_vocab[df_all_vocab['hsk_level']==current_hsk_level]
# df_this_hsk['priority'].value_counts()

# Most important HSK3: 62; HSK4: 72; HSK5: 34+99; HSK6: 24+70
# current_hsk_level = 6
# priority_limit = 2
# df_this_hsk = df_all_vocab[
#     (df_all_vocab['hsk_level']==current_hsk_level) &
#     (df_all_vocab['priority']<=priority_limit)
#     ]
# df_this_hsk.sample(10)

In [72]:
def filter_df_for_videos(df_all_vocab, data_settings):
    df_this_hsk = df_all_vocab[
        # (df_all_vocab['hsk_level']==int(data_settings['current_hsk_level'][0])) &
        (df_all_vocab['hsk_level']==data_settings['current_hsk_level']) &
        (df_all_vocab['priority']<=data_settings['priority_limit']) &
        (~df_all_vocab['chinese'].isin(data_settings['words_rmv']))
    ].sort_values(data_settings['sort_cols'], ascending=data_settings['sort_ascending']).reset_index(drop=True)
    return df_this_hsk
    

df_filt = filter_df_for_videos(df_all_vocab, data_settings)
print(df_filt['chinese'].values.tolist())
print(len(df_filt))
df_filt.head(10)

['牛', '建设', '桥', '衬衫', '普遍', '艺术', '工具', '自动', '空调', '设备', '标准', '专业', '去世', '值得', '吵架', '压力', '好奇', '适应', '关注', '理解', '游戏', '保险', '啤酒', '苹果', '香蕉', '糖', '营养', '性别', '搬家', '身份证', '话题', '情况', '类似', '交流', '困难', '各种', '具体', '特色', '通常', '海关', '体验', '错误', '上升', '升', '大约', '至少', '游泳', '取消', '输入', '退出', '技术', '文件', '以来', '卫生间', '组合', '退休', '老板', '创业', '人民币', '长城']
60

,id,chinese,pinyin,english,type,priority,category1,category2,cat_v3,cat2_v3,cat3_v3,hsk_level,known,known_pinyin_prompt,known_english_prompt,quality,word1,word1_english,word2,word2_english,word3,word3_english,word4,word4_english,voice_zh,voice_en,video_notes,sentence,sentence_pinyin,sentence_english,date,source1,source2,funny,per,adu,slang,phonetic
0,5897,牛,niú,cow,word,1,NaN,NaN,Animals,NaN,哺乳动物,3.0,5.0,2.0,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,农场里的牛在吃草,nóng chǎng lǐ de niú zài chī cǎo,The cows on the farm are grazing,2025-11-04,codenames,NaN,NaN,5.0,5.0,5.0,NaN
1,6333,建设,jiàn shè,construction;to build,word,1,NaN,NaN,Architecture & Infrastructure,NaN,NaN,3.0,5.0,5.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,城市建设速度非常快,chéng shì jiàn shè sù dù fēi cháng kuài,The city’s construction is progressing very qu...,2025-12-12,daily add,NaN,NaN,5.0,5.0,5.0,NaN
2,2991,桥,qiáo,bridge,word,1,travel,NaN,Architecture & Infrastructure,NaN,NaN,3.0,1.0,1.0,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我们走过一座桥,wǒ men zǒu guò yī zuò qiáo,we walked across a bridge,2025-02-10,ltl,NaN,NaN,5.0,5.0,5.0,NaN
3,5892,衬衫,chèn shān,shirt,word,1,NaN,NaN,Clothes & Accessories,NaN,上装,3.0,5.0,2.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,他今天穿了一件蓝色衬衫,tā jīn tiān chuān le yí jiàn lán sè chèn shān,He wore a blue shirt today,2025-11-04,codenames,NaN,NaN,5.0,5.0,5.0,NaN
4,6487,普遍,pǔ biàn,common,word,1,NaN,NaN,Culture & Society,NaN,NaN,3.0,5.0,5.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这种现象在城市里很普遍。,zhè zhǒng xiànxiàng zài chéngshì lǐ hěn pǔbiàn,This phenomenon is very common in cities.,2025-12-22,daily add,NaN,NaN,5.0,5.0,5.0,NaN
5,2125,艺术,yì shù,art,word,1,hobbies,NaN,Culture & Society,NaN,NaN,3.0,2.0,1.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,艺术可以让人们表达情感,Yìshù kěyǐ ràng rénmen biǎodá qínggǎn,Art allows people to express emotions,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
6,6004,工具,gōng jù,tool,word,1,NaN,NaN,Devices & Electronics,NaN,工具与维修设备,3.0,5.0,2.0,2.0,4.0,工作,work,具体,specific,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这些工具要放回工具箱里。,zhè xiē gōng jù yào fàng huí gōng jù xiāng lǐ.,These tools should be put back in the toolbox.,2025-11-04,codenames,NaN,NaN,5.0,5.0,5.0,NaN
7,144,自动,zì dòng,automatic,word,1,electronics,AI & Future Tech,Devices & Electronics,NaN,状态与描述,3.0,1.0,1.0,2.0,1.0,自,self,运动,to move,NaN,NaN,NaN,NaN,NaN,NaN,NaN,灯会在天黑的时候自动亮起,Dēng huì zài tiānhēi de shíhòu zìdòng liàngqǐ,The light turns on automatically when it gets ...,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
8,365,空调,kòng tiáo,air conditioning,word,1,electronics,Appliances & Everyday Electronics,Devices & Electronics,NaN,生活电器与环境调节,3.0,1.0,1.0,1.0,1.0,空气,air,调,adjust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,夏天开空调很舒服,xià tiān kāi kōng tiáo hěn shū fú,turning on the air conditioner in summer is ve...,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
9,867,设备,shè bèi,equipment,word,1,thing,NaN,Devices & Electronics,NaN,电子设备,3.0,5.0,2.0,2.0,3.0,设计,design,准备,preparation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这个设备很旧了,Zhège shèbèi hěn jiù le,This device is really old,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN

In [73]:
from edge_tts import Communicate
import os
voice_name = 'zh-CN-XiaoxiaoNeural'

start_time = time.time()
for row_i, current_row in df_filt.iterrows():
  mp3_path = f"output/tts/{voice_name}/{current_row['chinese']}.mp3"
  if os.path.exists(mp3_path):
     print(f'{mp3_path} exists')
  else:
    print(f"{current_row['chinese']}: {(time.time() - start_time):.2f}")
    communicate = Communicate(current_row['chinese'], voice_name)
    communicate.save_sync(mp3_path)

output/tts/zh-CN-XiaoxiaoNeural/牛.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/建设.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/桥.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/衬衫.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/普遍.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/艺术.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/工具.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/自动.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/空调.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/设备.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/标准.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/专业.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/去世.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/值得.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/吵架.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/压力.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/好奇.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/适应.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/关注.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/理解.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/游戏.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/保险.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/啤酒.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/苹果.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/香蕉.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/糖.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/营养.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/性别.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/搬家.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/身份证.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/话题.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/情况.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/类似.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/交流.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/困难.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/各种.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/具体.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/特色.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/通常.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/海关.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/体验.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/错误.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/上升.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/升.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/大约.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/至少.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/游泳.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/取消.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/输入.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/退出.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/技术.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/文件.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/以来.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/卫生间.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/组合.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/退休.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/老板.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/创业.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/人民币.mp3 exists
output/tts/zh-CN-XiaoxiaoNeural/长城.mp3 exists

# Create video for each part

In [74]:

from pydub import AudioSegment
def stitch_audios(audio_settings, data_settings, example_words):
    dict_audio_durations = defaultdict(list)
    if audio_settings['audio_plan'] == 'c2word':
        current_start_time = 0

        # beginning pause
        pause_beginning = AudioSegment.silent(duration=audio_settings['pause_ms_beginning'])
        combined = pause_beginning
        dict_audio_durations['audio_path'].append('pause_beginning')
        dict_audio_durations['duration'].append(audio_settings['pause_ms_beginning'] / 1000)
        dict_audio_durations['start_time'].append(current_start_time)
        current_start_time += audio_settings['pause_ms_beginning'] / 1000
        dict_audio_durations['end_time'].append(current_start_time)

        # words
        for _, word in enumerate(example_words):
            # word audio
            word_audio_path = f"output/tts/{audio_settings['voice_name_zh']}/{word}.mp3"
            audio = AudioSegment.from_mp3(word_audio_path)
            combined += audio 
            dict_audio_durations['audio_path'].append(word_audio_path)
            dict_audio_durations['duration'].append(audio.duration_seconds)
            dict_audio_durations['start_time'].append(current_start_time)
            current_start_time += audio.duration_seconds
            dict_audio_durations['end_time'].append(current_start_time)

            # within-word pause
            pause_within_word = AudioSegment.silent(duration=audio_settings['pause_ms_within_word'])
            combined += pause_within_word
            dict_audio_durations['audio_path'].append('within_word_pause')
            dict_audio_durations['duration'].append(audio_settings['pause_ms_within_word'] / 1000)
            dict_audio_durations['start_time'].append(current_start_time)
            current_start_time += audio_settings['pause_ms_within_word'] / 1000
            dict_audio_durations['end_time'].append(current_start_time)

            # word again audio
            combined += audio 
            dict_audio_durations['audio_path'].append(word_audio_path)
            dict_audio_durations['duration'].append(audio.duration_seconds)
            dict_audio_durations['start_time'].append(current_start_time)
            current_start_time += audio.duration_seconds
            dict_audio_durations['end_time'].append(current_start_time)

            # inter-word pause
            pause_inter_word = AudioSegment.silent(duration=audio_settings['pause_ms_between'])
            combined += pause_inter_word
            dict_audio_durations['audio_path'].append('inter_word_pause')
            dict_audio_durations['duration'].append(audio_settings['pause_ms_between'] / 1000)
            dict_audio_durations['start_time'].append(current_start_time)
            current_start_time += audio_settings['pause_ms_between'] / 1000
            dict_audio_durations['end_time'].append(current_start_time)
            

    # export the combined audio file
    combined.export(f"{data_settings['output_path_audio']}/!combined_part{data_settings['current_part']}.mp3", format="mp3")
    print(f'Audio duration: {combined.duration_seconds:.1f}s')

    # Add in static slide audio into dataframe of audio durations
    df_durations = pd.DataFrame(dict_audio_durations)
    return df_durations

In [75]:
print('Cut vocab into parts')
data_settings['n_words_total'] = len(df_filt)
data_settings['n_parts'] = int(np.ceil(len(df_filt) / data_settings['n_words_per_video']))

for current_part in range(1, data_settings['n_parts'] + 1):
    # Determine vocabulary in current part
    data_settings['current_part'] = current_part
    start_index = (current_part - 1) * data_settings['n_words_per_video']
    end_index = start_index + data_settings['n_words_per_video'] - 1
    data_settings['current_part_index_range'] = (start_index, end_index)
    print(f"Processing part {current_part}/{data_settings['n_parts']} with index range {data_settings['current_part_index_range']}")
    df_filt_currentpart = df_filt[
        (df_filt.index >= data_settings['current_part_index_range'][0]) &
        (df_filt.index <= data_settings['current_part_index_range'][1])
    ].reset_index(drop=True)

    print('Making audio')
    df_durations = stitch_audios(audio_settings, data_settings, df_filt_currentpart['chinese'].values.tolist())

    print('Making image')
    no_hl_img_file_path = draw_vocab_list_whole_image(video_configs, data_settings, df_filt_currentpart, title_format=video_configs['title_format'])
    print('Making video without highlights')
    create_video_without_highlights(data_settings, video_configs, no_hl_img_file_path)
    print('Making video with highlights')
    create_video_with_highlights(df_durations, audio_settings, data_settings, video_configs, method_to_determine_highlight_timing=None, highlight_start_ids=np.arange(1,len(df_durations), 4))
    break

Cut vocab into parts
Processing part 1/6 with index range (0, 9)
Making audio

frame_index:  34%|███▍      | 254/742 [00:10<00:09, 50.84it/s, now=None]

Audio duration: 30.9s
Making image
Making video without highlights
MoviePy - Building video output/hsk_top_shorts//hsk3_no_highlights_part1.mp4.
MoviePy - Writing audio in hsk3_no_highlights_part1TEMP_MPY_wvf_snd.mp3

frame_index:  34%|███▍      | 254/742 [00:10<00:09, 50.84it/s, now=None]

MoviePy - Done.
MoviePy - Writing video output/hsk_top_shorts//hsk3_no_highlights_part1.mp4

frame_index:  34%|███▍      | 254/742 [00:24<00:09, 50.84it/s, now=None]

MoviePy - Done !
MoviePy - video ready output/hsk_top_shorts//hsk3_no_highlights_part1.mp4
Making video with highlights
MoviePy - Building video output/hsk_top_shorts//hsk3_part1.mp4.
MoviePy - Writing audio in hsk3_part1TEMP_MPY_wvf_snd.mp3

frame_index:  34%|███▍      | 254/742 [00:24<00:09, 50.84it/s, now=None]

MoviePy - Done.
MoviePy - Writing video output/hsk_top_shorts//hsk3_part1.mp4

KeyboardInterrupt:

In [60]:
df_filt

,id,chinese,pinyin,english,type,priority,category1,category2,cat_v3,cat2_v3,cat3_v3,hsk_level,known,known_pinyin_prompt,known_english_prompt,quality,word1,word1_english,word2,word2_english,word3,word3_english,word4,word4_english,voice_zh,voice_en,video_notes,sentence,sentence_pinyin,sentence_english,date,source1,source2,funny,per,adu,slang,phonetic
0,5897,牛,niú,cow,word,1,NaN,NaN,Animals,NaN,哺乳动物,3.0,5.0,2.0,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,农场里的牛在吃草,nóng chǎng lǐ de niú zài chī cǎo,The cows on the farm are grazing,2025-11-04,codenames,NaN,NaN,5.0,5.0,5.0,NaN
1,6333,建设,jiàn shè,construction;to build,word,1,NaN,NaN,Architecture & Infrastructure,NaN,NaN,3.0,5.0,5.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,城市建设速度非常快,chéng shì jiàn shè sù dù fēi cháng kuài,The city’s construction is progressing very qu...,2025-12-12,daily add,NaN,NaN,5.0,5.0,5.0,NaN
2,2991,桥,qiáo,bridge,word,1,travel,NaN,Architecture & Infrastructure,NaN,NaN,3.0,1.0,1.0,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我们走过一座桥,wǒ men zǒu guò yī zuò qiáo,we walked across a bridge,2025-02-10,ltl,NaN,NaN,5.0,5.0,5.0,NaN
3,5892,衬衫,chèn shān,shirt,word,1,NaN,NaN,Clothes & Accessories,NaN,上装,3.0,5.0,2.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,他今天穿了一件蓝色衬衫,tā jīn tiān chuān le yí jiàn lán sè chèn shān,He wore a blue shirt today,2025-11-04,codenames,NaN,NaN,5.0,5.0,5.0,NaN
4,6487,普遍,pǔ biàn,common,word,1,NaN,NaN,Culture & Society,NaN,NaN,3.0,5.0,5.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这种现象在城市里很普遍。,zhè zhǒng xiànxiàng zài chéngshì lǐ hěn pǔbiàn,This phenomenon is very common in cities.,2025-12-22,daily add,NaN,NaN,5.0,5.0,5.0,NaN
5,2125,艺术,yì shù,art,word,1,hobbies,NaN,Culture & Society,NaN,NaN,3.0,2.0,1.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,艺术可以让人们表达情感,Yìshù kěyǐ ràng rénmen biǎodá qínggǎn,Art allows people to express emotions,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
6,6004,工具,gōng jù,tool,word,1,NaN,NaN,Devices & Electronics,NaN,工具与维修设备,3.0,5.0,2.0,2.0,4.0,工作,work,具体,specific,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这些工具要放回工具箱里。,zhè xiē gōng jù yào fàng huí gōng jù xiāng lǐ.,These tools should be put back in the toolbox.,2025-11-04,codenames,NaN,NaN,5.0,5.0,5.0,NaN
7,144,自动,zì dòng,automatic,word,1,electronics,AI & Future Tech,Devices & Electronics,NaN,状态与描述,3.0,1.0,1.0,2.0,1.0,自,self,运动,to move,NaN,NaN,NaN,NaN,NaN,NaN,NaN,灯会在天黑的时候自动亮起,Dēng huì zài tiānhēi de shíhòu zìdòng liàngqǐ,The light turns on automatically when it gets ...,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
8,365,空调,kòng tiáo,air conditioning,word,1,electronics,Appliances & Everyday Electronics,Devices & Electronics,NaN,生活电器与环境调节,3.0,1.0,1.0,1.0,1.0,空气,air,调,adjust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,夏天开空调很舒服,xià tiān kāi kōng tiáo hěn shū fú,turning on the air conditioner in summer is ve...,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
9,867,设备,shè bèi,equipment,word,1,thing,NaN,Devices & Electronics,NaN,电子设备,3.0,5.0,2.0,2.0,3.0,设计,design,准备,preparation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这个设备很旧了,Zhège shèbèi hěn jiù le,This device is really old,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
10,1024,标准,biāo zhǔn,standard,word,1,adjective,Clarity & Specificity,Education & Learning,NaN,学术概念与理论,3.0,5.0,1.0,1.0,3.0,目标,target,准备,preparation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这家店的服务很标准,Zhè jiā diàn de fúwù hěn biāozhǔn,The service here is very standard,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
11,746,专业,zhuān yè,major;specialty,word,1,career,Education,Education & Learning,NaN,课程与培养方案,3.0,2.0,1.0,1.0,2.0,专家,expert,业,industry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,她的专业是数据科学,tā de zhuān yè shì shù jù kē xué,her major is data science,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
12,775,去世,qù shì,to die;pass away,word,1,life,NaN,Emotions & Relationships,NaN,人生阶段,3.0,2.0,1.0,1.0,2.0,去,to leave,世界,world,NaN,NaN,NaN,NaN,NaN,NaN,NaN,他去世了,tā qù shì le,He passed away,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
13,673,值得,zhí dé,to be worth;deserve,word,1,society,NaN,Emotions & Relationships,NaN,价值判断,3.0,5.0,1.0,2.0,2.0,值,value,得,to get,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这个博物馆很值得一去,Zhège bówùguǎn hěn zhídé yī qù,This museum is worth visiting,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
14,498,吵架,chǎo jià,to quarrel;fight,word,1,feeling,NaN,Emotions & Relationships,NaN,冲突与矛盾,3.0,4.0,1.0,2.0,3.0,吵,noisy,绑架,to kidnap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,他们又吵架了,Tāmen yòu chǎojià le,They argued again,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
15,2085,压力,yā lì,pressure,word,1,feeling,NaN,Emotions & Relationships,NaN,心理压力,3.0,1.0,1.0,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,工作压力很大,gōng zuò yā lì hěn dà,work pressure is very high,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
16,649,好奇,hào qí,curious,word,1,feeling,NaN,Emotions & Relationships,NaN,心理状态,3.0,2.0,1.0,1.0,2.0,好,good,奇怪,strange,NaN,NaN,NaN,NaN,NaN,NaN,NaN,小孩对一切都很好奇,xiǎo hái duì yī qiè dōu hěn hào qí,children are curious about everything,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
17,696,适应,shì yìng,to adapt;get used to,word,1,feeling,NaN,Emotions & Relationships,NaN,成长与变化,3.0,5.0,5.0,2.0,3.0,适合,to suit,应该,should,NaN,NaN,NaN,NaN,NaN,NaN,NaN,你适应新环境了吗,Nǐ shìyìng xīn huánjìng le ma,Have you adapted to the new environment,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
18,2260,关注,guān zhù,focus on;to follow,word,1,people,NaN,Emotions & Relationships,NaN,照顾与关怀,3.0,5.0,2.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我很关注这件事,Wǒ hěn guānzhù zhè jiàn shì,I care a lot about this matter,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
19,499,理解,lǐ jiě,to understand,word,1,verb,NaN,Emotions & Relationships,NaN,理解与误解,3.0,5.0,3.0,2.0,5.0,管理,to manage,解决,to resolve,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我完全理解你的想法,Wǒ wánquán lǐjiě nǐ de xiǎngfǎ,I totally understand your thinking,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
20,744,游戏,yóu xì,game,word,1,hobbies,NaN,Entertainment,NaN,游戏与娱乐活动,3.0,1.0,1.0,1.0,3.0,旅游,to travel,演戏,to perform,NaN,NaN,NaN,NaN,NaN,NaN,NaN,他喜欢玩电脑游戏,tā xǐ huān wán diàn nǎo yóu xì,he likes playing computer games,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
21,5,保险,bǎo xiǎn,insurance,word,1,life,NaN,Finance & Economy,NaN,保险与保障,3.0,1.0,1.0,2.0,1.0,保护,protect,危险,danger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,没有保险看病很贵,Méiyǒu bǎoxiǎn kànbìng hěn guì,It is expensive to see a doctor without insurance,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
22,5823,啤酒,pí jiǔ,beer,word,1,NaN,NaN,Food & Drink,NaN,蔬菜类,3.0,5.0,2.0,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,他喝了两瓶啤酒,tā hē le liǎng píng pí jiǔ,he drank two bottles of beer,2025-11-04,codenames,NaN,NaN,5.0,5.0,5.0,NaN
23,6010,苹果,píng guǒ,apple,word,1,NaN,NaN,Food & Drink,NaN,蔬菜类,3.0,5.0,2.0,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我最喜欢吃红苹果。,wǒ zuì xǐ huan chī hóng píng guǒ.,I like eating red apples the most.,2025-11-04,codenames,NaN,NaN,5.0,5.0,5.0,NaN
24,5998,香蕉,xiāng jiāo,banana,word,1,NaN,NaN,Food & Drink,NaN,蔬菜类,3.0,5.0,2.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,他早餐吃了一根香蕉。,tā zǎo cān chī le yì gēn xiāng jiāo.,He ate a banana for breakfast.,2025-11-04,codenames,NaN,NaN,5.0,5.0,5.0,NaN
25,5941,糖,táng,sugar,word,1,NaN,NaN,Food & Drink,NaN,零食与小吃,3.0,5.0,2.0,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,别吃太多糖对牙不好,bié chī tài duō táng duì yá bù hǎo,Don’t eat too much sugar it’s bad for your teeth,2025-11-04,codenames,NaN,NaN,5.0,5.0,5.0,NaN
26,938,营养,yíng yǎng,nutrition,word,1,food,NaN,Food & Drink,NaN,餐饮场所与品牌,3.0,5.0,2.0,2.0,3.0,营,camp,养,to raise,NaN,NaN,NaN,NaN,NaN,NaN,NaN,早餐要有营养,Zǎocān yào yǒu yíngyǎng,Breakfast should be nutritious,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
27,897,性别,xìng bié,gender,word,1,health,reproductive health,Health & Body,NaN,生殖与性健康,3.0,2.0,1.0,1.0,2.0,性,nature,分别,to distinguish,NaN,NaN,NaN,NaN,NaN,NaN,NaN,请在表格上填写你的性别,Qǐng zài biǎogé shàng tiánxiě nǐ de xìngbié,Please fill in your gender on the form,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
28,3904,搬家,bān jiā,to move (home),word,1,life,NaN,Home & Appliances & Housing,NaN,居住行为与生活状态,3.0,2.0,1.0,1.0,4.0,搬,to move;relocate,家,house,NaN,NaN,NaN,NaN,NaN,NaN,NaN,下个月我们要搬家,xià gè yuè wǒ men yào bān jiā,we are moving next month,2025-07-09,daily add,NaN,NaN,5.0,5.0,5.0,NaN
29,1180,身份证,shēn fèn zhèng,ID card,word,1,society,NaN,Identity & People,NaN,基本身份与个人信息,3.0,2.0,1.0,1.0,3.0,身份,identity,证书,certificate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,办理需要身份证,Bànlǐ xūyào shēnfènzhèng,You need an ID card to process this,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
30,2106,话题,huà tí,topic,word,1,noun,NaN,Language & Expression,modal particle,信息与内容,3.0,2.0,1.0,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,他们换了一个新的话题,tā men huàn le yī gè xīn de huà tí,they changed to a new topic,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
31,5920,情况,qíng kuàng,situation,word,1,NaN,NaN,Language & Expression,NaN,信息与内容,3.0,5.0,2.0,2.0,5.0,情,feeling,状况,condition,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我们需要了解最新的情况,wǒ men xū yào liǎo jiě zuì xīn de qíng kuàng,We need to know the latest situation,2025-11-04,codenames,NaN,NaN,5.0,5.0,5.0,NaN
32,1669,类似,lèi sì,similar,word,1,general,NaN,Language & Expression,NaN,比较与差异,3.0,5.0,2.0,2.0,2.0,类,kind,似乎,to seem,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这两个产品很类似,Zhè liǎng gè chǎnpǐn hěn lèisì,These two products are very similar,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
33,1381,交流,jiāo liú,communication,word,1,people,NaN,Language & Expression,NaN,沟通与对话行为,3.0,5.0,2.0,2.0,4.0,交通,traffic,流,to flow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我们经常交流想法,Wǒmen jīngcháng jiāoliú xiǎngfǎ,We often share ideas,2025-06-09,NaN,NaN,NaN,5.0,5.0,5.0,NaN
34,662,困难,kùn nán,difficult;challenging,word,1,feeling,NaN,Language & Expression,NaN,状态与变化,3.0,2.0,1.0,2.0,2.0,困,tired,难,hard,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这任务很困难,Zhè rènwu hěn kùnnán,This task is hard,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
35,883,各种,gè zhǒng,various types;all kinds,word,1,characteristic,Other,Language & Expression,NaN,程度与范围,3.0,4.0,2.0,1.0,3.0,各,each,种,type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我喜欢各种口味的冰淇淋,Wǒ xǐhuān gèzhǒng kǒuwèi de bīngqílín,I like ice cream of all flavors,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
36,126,具体,jù tǐ,specific;concrete;definite,word,1,adjective,Clarity & Specificity,Language & Expression,NaN,程度与范围,3.0,3.0,1.0,2.0,3.0,具,tool,身体,body,NaN,NaN,NaN,NaN,NaN,NaN,NaN,能说得具体一点吗,Néng shuō de jùtǐ yīdiǎn ma,Can you be more specific,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
37,726,特色,tè sè,characteristic;distinguishing feature,word,1,shopping,NaN,Language & Expression,NaN,评价性词汇（褒贬）,3.0,1.0,1.0,2.0,3.0,特,special,色,color,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这个小镇很有特色,Zhège xiǎo zhèn hěn yǒu tèsè,This town has unique features,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
38,2752,通常,tōng​ cháng,generally;usually,word,1,amount,time,Language & Expression,NaN,频率与习惯,3.0,3.0,2.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我通常早起,Wǒ tōngcháng zǎoqǐ,I usually wake up early,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
39,646,海关,hǎi guān,customs,word,1,travel,NaN,Law & Security,NaN,执法与公共安全机构,3.0,1.0,1.0,1.0,2.0,海,sea,关,to close,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我们在机场经过海关,wǒ men zài jī chǎng jīng guò hǎi guān,we passed through customs at the airport,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
40,732,体验,tǐ yàn,to personally experience,word,1,general,NaN,Lifestyle,NaN,生活方式与态度,3.0,3.0,2.0,2.0,3.0,体,body,经验,to experience,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我想体验一下当地生活,Wǒ xiǎng tǐyàn yīxià dāngdì shēnghuó,I want to experience local life,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
41,5877,错误,cuò wù,error,word,1,NaN,NaN,Lifestyle,NaN,评价与判断,3.0,5.0,2.0,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我们从错误中学习,wǒ men cóng cuò wù zhōng xué xí,We learn from mistakes,2025-11-04,codenames,NaN,NaN,5.0,5.0,5.0,NaN
42,3937,上升,shàng shēng,rise;ascent;increased,word,1,change,Increase/Growth,Numbers & Measurement,NaN,变化与趋势,3.0,5.0,2.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,温度正在上升,Wēndù zhèngzài shàngshēng,The temperature is rising,2025-07-10,daily add,NaN,NaN,5.0,5.0,5.0,NaN
43,3936,升,shēng,liter;to rise;go up,word,1,amount,measure,Numbers & Measurement,NaN,度量单位（物理/能量/长度等）,3.0,5.0,2.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,水温升高了,Shuǐwēn shēng gāo le,The water temperature went up,2025-07-10,daily add,NaN,NaN,5.0,5.0,5.0,NaN
44,1641,大约,dà yuē,about;approximately,word,1,general,NaN,Numbers & Measurement,NaN,数量与数值表达,3.0,2.0,2.0,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我大约五点到,Wǒ dàyuē wǔ diǎn dào,I will arrive around five,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
45,1023,至少,zhì shǎo,at least,word,1,amount,number,Numbers & Measurement,NaN,范围・比较关系,3.0,3.0,1.0,1.0,3.0,至,until,少,few,NaN,NaN,NaN,NaN,NaN,NaN,NaN,今天至少要完成一半,Jīntiān zhìshǎo yào wánchéng yībàn,We need to finish at least half today,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
46,5808,游泳,yóu yǒng,swim,word,1,NaN,NaN,Sports & Fitness,NaN,运动项目,3.0,5.0,2.0,2.0,4.0,游戏,game,泳池,pool;pond,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我每周去游泳两次,wǒ měi zhōu qù yóu yǒng liǎng cì,I go swimming twice a week,2025-11-04,codenames,NaN,NaN,5.0,5.0,5.0,NaN
47,491,取消,qǔ xiāo,to cancel;cancellation,word,1,general,NaN,Technology & Internet,NaN,基础操作与状态,3.0,5.0,2.0,2.0,2.0,取得,to get,消失,to disappear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我取消了订单,Wǒ qǔxiāo le dìngdān,I canceled the order,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
48,1350,输入,shū rù,to input,word,1,electronics,User Actions & Interface,Technology & Internet,NaN,基础操作与状态,3.0,5.0,2.0,2.0,3.0,运输,to transport,入,enter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,请在这里输入密码,Qǐng zài zhèlǐ shūrù mìmǎ,Please enter the password here,2025-06-08,NaN,NaN,NaN,5.0,5.0,5.0,NaN
49,1429,退出,tuì chū,to quit (program),word,1,career,Work Conditions,Technology & Internet,NaN,基础操作与状态,3.0,5.0,5.0,5.0,3.0,退,to retreat,出,to go out,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我决定退出比赛,Wǒ juédìng tuìchū bǐsài,I decided to quit the competition,2025-06-15,NaN,NaN,NaN,5.0,5.0,5.0,NaN
50,942,技术,jì shù,technology,word,1,career,Technology & Engineering,Technology & Internet,NaN,技术与开发,3.0,5.0,1.0,2.0,2.0,技,skill,术,art,NaN,NaN,NaN,NaN,NaN,NaN,NaN,他掌握了很多先进的技术,Tā zhǎngwò le hěn duō xiānjìn de jìshù,He has mastered many advanced technologies,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
51,785,文件,wén jiàn,document;file,word,1,career,Documents & Tasks,Technology & Internet,NaN,数据与文件,3.0,2.0,1.0,5.0,2.0,文,writing,件,piece,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我保存了文件,Wǒ bǎocún le wénjiàn,I saved the file,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
52,929,以来,yǐ lái,since (previous event),word,1,time,NaN,Time,NaN,时间顺序与先后,3.0,5.0,2.0,2.0,3.0,以前,before,来,to come,NaN,NaN,NaN,NaN,NaN,NaN,NaN,我认识你以来都很开心,Wǒ rènshi nǐ yǐlái dōu hěn kāixīn,I've been happy since I met you,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
53,2823,卫生间,wèi shēng jiān,bathroom,word,1,life,NaN,Travel & Geography,NaN,住宿与酒店相关,3.0,1.0,1.0,1.0,2.0,卫生,hygiene,间,room,NaN,NaN,NaN,NaN,NaN,NaN,NaN,卫生间在右边,wèi shēng jiān zài yòu biān,the restroom is on the right,2025-02-10,ltl,NaN,NaN,5.0,5.0,5.0,NaN
54,4,组合,zǔ hé,combination,word,1,general,NaN,Work & Career,NaN,团队与组织,3.0,5.0,2.0,2.0,2.0,组,set,合适,suitable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,这个组合在比赛中获得了第一名。,Zhège zǔhé zài bǐsài zhōng huòdé le dì yī míng.,This group won first place in the competition.,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
55,773,退休,tuì xiū,to retire,word,1,career,Work Conditions,Work & Career,NaN,工作状态/工作安排,3.0,1.0,1.0,2.0,2.0,退,to retreat,休,to rest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,他计划明年退休,Tā jìhuà míngnián tuìxiū,He plans to retire next year,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
56,771,老板,lǎo bǎn,boss,word,1,career,People & Roles,Work & Career,NaN,管理职位,3.0,1.0,1.0,2.0,3.0,老,old,板,plank;board,NaN,NaN,NaN,NaN,NaN,NaN,NaN,老板今天请客,Lǎobǎn jīntiān qǐngkè,The boss is treating today,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
57,9,创业,chuàng yè,entrepreneurship,word,1,career,Business & Finance,Work & Career,NaN,行业/公司类型,3.0,2.0,1.0,2.0,2.0,创造,to create,企业,company,NaN,NaN,NaN,NaN,NaN,NaN,NaN,他在大学期间就开始创业,Tā zài dàxué qījiān jiù kāishǐ chuàngyè,He started a business during college,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
58,1086,人民币,rén mín bì,Chinese yuan;RMB,word,1,china,Modern Society & Lifestyle,my_china,NaN,NaN,3.0,1.0,1.0,1.0,2.0,人民,the people,货币,currency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,他用人民币付款,tā yòng rén mín bì fù kuǎn,he paid with RMB,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
59,6793,长城,cháng chéng,The Great Wall of China,proper noun,1,NaN,NaN,my_china_spots,NaN,NaN,3.0,5.0,5.0,1.0,3.0,长,long,城墙,city wall,NaN,NaN,NaN,NaN,NaN,NaN,NaN,第一次站在长城上，我被它的规模震撼了。,"dì yī cì zhàn zài cháng chéng shàng, wǒ bèi tā...","The first time I stood on the Great Wall, I wa...",2025-12-30,china places,NaN,NaN,5.0,5.0,5.0,NaN

In [61]:
df_durations.head(10)

                               audio_path  duration  start_time  end_time
0                         pause_beginning     0.150       0.000     0.150
1   output/tts/zh-CN-XiaoxiaoNeural/牛.mp3     0.984       0.150     1.134
2                       within_word_pause     0.200       1.134     1.334
3   output/tts/zh-CN-XiaoxiaoNeural/牛.mp3     0.984       1.334     2.318
4                        inter_word_pause     0.500       2.318     2.818
5  output/tts/zh-CN-XiaoxiaoNeural/建设.mp3     1.296       2.818     4.114
6                       within_word_pause     0.200       4.114     4.314
7  output/tts/zh-CN-XiaoxiaoNeural/建设.mp3     1.296       4.314     5.610
8                        inter_word_pause     0.500       5.610     6.110
9   output/tts/zh-CN-XiaoxiaoNeural/桥.mp3     1.056       6.110     7.166